[package]
name = "calstack-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
toml.workspace = true
url = "2"
ical = { version = "0.11", default-features = false, features = ["ical"] }
rrule = { version = "0.14", features = ["exrule"] }
chrono-tz = "0.10"
windows-timezones = "0.5"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
serde_json = "1"
sha2 = "0.10"
